### ISSUE TITLE
localhost:4000 responds with 404 (Not Found)

### ISSUE THREAD

**Issue by malchak** [rynclark/flux-getting-started#1]
Hi Ryan,

Thanks for the great blog post!  I'm trying to get the starter repo up and running, but am getting a 404 (Not Found) after running "gulp".

This is the output from my terminal:
`[20:47:22] Starting 'server'...`
`[20:47:22] Finished 'server' after 2.32 ms`
`[20:47:22] Starting 'scripts'...`
`[20:47:22] Starting 'styles'...`
`[20:47:22] Starting 'copy:libs'...`
`[20:47:22] Finished 'copy:libs' after 2.95 ms`
`[20:47:22] Starting 'copy:html'...`
`[20:47:22] Starting 'watch'...`
`[20:47:22] Finished 'watch' after 14 ms`
`[20:47:22] Finished 'copy:html' after 53 ms`
`[20:47:22] app.js was reloaded.`
`[20:47:22] Finished 'scripts' after 242 ms`
`[20:47:22] gulp-ruby-sass: directory`
`[20:47:23] gulp-ruby-sass: write app.css`
`[20:47:23] gulp-ruby-sass: write app.css.map`
`[20:47:23] Finished 'styles' after 1.13 s`
`[20:47:23] Starting 'build'...`
`[20:47:23] Finished 'build' after 4.13 μs`
`[20:47:23] Starting 'default'...`
`[20:47:23] Finished 'default' after 5.74 μs`
`[20:47:23] app.css was reloaded.`

I feel like something may be missing, but I can't pinpoint the issue.  Thoughts?

**Comment by cdb** [comment]
I'm finding the same issue - I think perhaps there's a basic index.html that's missing? I see "index.html" in the .gitignore file, which maybe wasn't intended?

**Comment by ryanclark** [comment]
Oops - removed index.html from the .gitignore and pushed it to all branches!

**Comment by hbi99** [comment]
Similar issue for me; two log entries from the console:

GET http://localhost:4000/js/react-with-addons.js 404 (Not Found)
Uncaught ReferenceError: React is not defined

**Comment by hbi99** [comment]
It seems to be some issue with "react-bower.git"

**Comment by ryanclark** [comment]
Have you ran "bower install"?

**Comment by amitport** [comment]
I had the same symptoms. `bower install` tried to use _git_ protocol, but it was blocked by the firewall. I had to run*:

```
git config --global url."https://".insteadOf git://
```

\* before running this, make sure that `%HOME%` is the same as `%USERPROFILE%`. This is required because git uses `%HOME%` to save the config, while bower uses `%USERPROFILE%` to read it.
