### ISSUE TITLE
gulp-ruby-sass error at _messageBox.scss

### ISSUE THREAD

**Issue by giovannibonetti** [rynclark/flux-getting-started#2]
Hi! I was eager to try out this project, but after running gulp I've got this error:

[14:35:20] Plumber found unhandled error: Error in plugin 'gulp-ruby-sass'
Message:
    error /Users/gkbonetti/code/flux-getting-started/public/src/scss/partials/_messageBox.scss (Line 3: Invalid CSS after " &": expected "{", was "__list {"

"__list" may only be used at the beginning of a compound selector.)

I am new to React, but have a lot of experience with Ruby, SASS and AngularJS.
What am I doing wrong?

**Comment by ryanclark** [comment]
You'll need to update your SASS to the latest as you're getting a BEM error!
